/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivayRouteImport } from './routes/privay'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiTranscribeVoiceRouteImport } from './routes/api/transcribe-voice'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiGenerationStatusRouteImport } from './routes/api/generation-status'
import { Route as ApiGenerateBriefRouteImport } from './routes/api/generate-brief'
import { Route as ApiDeleteAccountRouteImport } from './routes/api/delete-account'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBriefsRouteImport } from './routes/_authenticated/briefs'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as AuthenticatedBriefNewRouteImport } from './routes/_authenticated/brief.new'
import { Route as AuthenticatedBriefIdEditRouteImport } from './routes/_authenticated/brief.$id.edit'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivayRoute = PrivayRouteImport.update({
  id: '/privay',
  path: '/privay',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const ApiTranscribeVoiceRoute = ApiTranscribeVoiceRouteImport.update({
  id: '/api/transcribe-voice',
  path: '/api/transcribe-voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerationStatusRoute = ApiGenerationStatusRouteImport.update({
  id: '/api/generation-status',
  path: '/api/generation-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateBriefRoute = ApiGenerateBriefRouteImport.update({
  id: '/api/generate-brief',
  path: '/api/generate-brief',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeleteAccountRoute = ApiDeleteAccountRouteImport.update({
  id: '/api/delete-account',
  path: '/api/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBriefsRoute = AuthenticatedBriefsRouteImport.update({
  id: '/briefs',
  path: '/briefs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBriefNewRoute = AuthenticatedBriefNewRouteImport.update({
  id: '/brief/new',
  path: '/brief/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBriefIdEditRoute =
  AuthenticatedBriefIdEditRouteImport.update({
    id: '/brief/$id/edit',
    path: '/brief/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/delete-account': typeof DeleteAccountRoute
  '/demo': typeof DemoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/privay': typeof PrivayRoute
  '/reset-password': typeof ResetPasswordRoute
  '/briefs': typeof AuthenticatedBriefsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/delete-account': typeof ApiDeleteAccountRoute
  '/api/generate-brief': typeof ApiGenerateBriefRoute
  '/api/generation-status': typeof ApiGenerationStatusRoute
  '/api/health': typeof ApiHealthRoute
  '/api/transcribe-voice': typeof ApiTranscribeVoiceRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/brief/new': typeof AuthenticatedBriefNewRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/brief/$id/edit': typeof AuthenticatedBriefIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/delete-account': typeof DeleteAccountRoute
  '/demo': typeof DemoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/privay': typeof PrivayRoute
  '/reset-password': typeof ResetPasswordRoute
  '/briefs': typeof AuthenticatedBriefsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/delete-account': typeof ApiDeleteAccountRoute
  '/api/generate-brief': typeof ApiGenerateBriefRoute
  '/api/generation-status': typeof ApiGenerationStatusRoute
  '/api/health': typeof ApiHealthRoute
  '/api/transcribe-voice': typeof ApiTranscribeVoiceRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/brief/new': typeof AuthenticatedBriefNewRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/brief/$id/edit': typeof AuthenticatedBriefIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/delete-account': typeof DeleteAccountRoute
  '/demo': typeof DemoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/privay': typeof PrivayRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/briefs': typeof AuthenticatedBriefsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/delete-account': typeof ApiDeleteAccountRoute
  '/api/generate-brief': typeof ApiGenerateBriefRoute
  '/api/generation-status': typeof ApiGenerationStatusRoute
  '/api/health': typeof ApiHealthRoute
  '/api/transcribe-voice': typeof ApiTranscribeVoiceRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/brief/new': typeof AuthenticatedBriefNewRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/_authenticated/brief/$id/edit': typeof AuthenticatedBriefIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/delete-account'
    | '/demo'
    | '/forgot-password'
    | '/privay'
    | '/reset-password'
    | '/briefs'
    | '/dashboard'
    | '/api/delete-account'
    | '/api/generate-brief'
    | '/api/generation-status'
    | '/api/health'
    | '/api/transcribe-voice'
    | '/auth/callback'
    | '/brief/new'
    | '/api/auth/login'
    | '/brief/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/delete-account'
    | '/demo'
    | '/forgot-password'
    | '/privay'
    | '/reset-password'
    | '/briefs'
    | '/dashboard'
    | '/api/delete-account'
    | '/api/generate-brief'
    | '/api/generation-status'
    | '/api/health'
    | '/api/transcribe-voice'
    | '/auth/callback'
    | '/brief/new'
    | '/api/auth/login'
    | '/brief/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/delete-account'
    | '/demo'
    | '/forgot-password'
    | '/privay'
    | '/reset-password'
    | '/_authenticated/briefs'
    | '/_authenticated/dashboard'
    | '/api/delete-account'
    | '/api/generate-brief'
    | '/api/generation-status'
    | '/api/health'
    | '/api/transcribe-voice'
    | '/auth/callback'
    | '/_authenticated/brief/new'
    | '/api/auth/login'
    | '/_authenticated/brief/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DeleteAccountRoute: typeof DeleteAccountRoute
  DemoRoute: typeof DemoRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  PrivayRoute: typeof PrivayRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiDeleteAccountRoute: typeof ApiDeleteAccountRoute
  ApiGenerateBriefRoute: typeof ApiGenerateBriefRoute
  ApiGenerationStatusRoute: typeof ApiGenerationStatusRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiTranscribeVoiceRoute: typeof ApiTranscribeVoiceRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privay': {
      id: '/privay'
      path: '/privay'
      fullPath: '/privay'
      preLoaderRoute: typeof PrivayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/transcribe-voice': {
      id: '/api/transcribe-voice'
      path: '/api/transcribe-voice'
      fullPath: '/api/transcribe-voice'
      preLoaderRoute: typeof ApiTranscribeVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generation-status': {
      id: '/api/generation-status'
      path: '/api/generation-status'
      fullPath: '/api/generation-status'
      preLoaderRoute: typeof ApiGenerationStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-brief': {
      id: '/api/generate-brief'
      path: '/api/generate-brief'
      fullPath: '/api/generate-brief'
      preLoaderRoute: typeof ApiGenerateBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/delete-account': {
      id: '/api/delete-account'
      path: '/api/delete-account'
      fullPath: '/api/delete-account'
      preLoaderRoute: typeof ApiDeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/briefs': {
      id: '/_authenticated/briefs'
      path: '/briefs'
      fullPath: '/briefs'
      preLoaderRoute: typeof AuthenticatedBriefsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/brief/new': {
      id: '/_authenticated/brief/new'
      path: '/brief/new'
      fullPath: '/brief/new'
      preLoaderRoute: typeof AuthenticatedBriefNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brief/$id/edit': {
      id: '/_authenticated/brief/$id/edit'
      path: '/brief/$id/edit'
      fullPath: '/brief/$id/edit'
      preLoaderRoute: typeof AuthenticatedBriefIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBriefsRoute: typeof AuthenticatedBriefsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedBriefNewRoute: typeof AuthenticatedBriefNewRoute
  AuthenticatedBriefIdEditRoute: typeof AuthenticatedBriefIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBriefsRoute: AuthenticatedBriefsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedBriefNewRoute: AuthenticatedBriefNewRoute,
  AuthenticatedBriefIdEditRoute: AuthenticatedBriefIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DeleteAccountRoute: DeleteAccountRoute,
  DemoRoute: DemoRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  PrivayRoute: PrivayRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiDeleteAccountRoute: ApiDeleteAccountRoute,
  ApiGenerateBriefRoute: ApiGenerateBriefRoute,
  ApiGenerationStatusRoute: ApiGenerationStatusRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiTranscribeVoiceRoute: ApiTranscribeVoiceRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
